### ISSUE TITLE
make: *** No rule to make target 'diamondcalculator.cpp', needed by 'seing'. Stop.

### ISSUE THREAD

**Issue by lukasturcani** [mreveil/seing#1]
Hi, 

Thank you for this library! I think maybe "diamondcalculator.cpp" was not commited to the repo as my 
"make seing" command outputs the error message:

make: *** No rule to make target 'diamondcalculator.cpp', needed by 'seing'. Stop.

It looks like it is a dependency for both "genericlocalcalculator" and "gaussiancalculator". 

Thanks,

Lukas

**Comment by mreveil** [comment]
Hi Lukas, Thanks for reporting this issue. 

"diamondcalculator.cpp" was a test calculator and is not really required for SEING to work. All related references have been removed and the repository updated. Please confirm that you are now able to compile the code.

Thanks,

Mardochee

**Comment by lukasturcani** [comment]
Yes, works fine now.

Many thanks,

Lukas
